/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiIndexSplatRouteImport } from './routes/api/index.$'
import { Route as ManagerWorkshopsIndexRouteImport } from './routes/manager/workshops/index'
import { Route as ManagerSessionsIndexRouteImport } from './routes/manager/sessions/index'
import { Route as AppSessionIdParticipantIdRouteImport } from './routes/app/$sessionId.$participantId'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ManagerWorkshopsWorkshopIdIndexRouteImport } from './routes/manager/workshops/$workshopId/index'
import { Route as ManagerSessionsSessionIdIndexRouteImport } from './routes/manager/sessions/$sessionId/index'
import { Route as ManagerWorkshopsWorkshopIdStepsStepIdIndexRouteImport } from './routes/manager/workshops/$workshopId/steps/$stepId/index'
import { Route as ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRouteImport } from './routes/manager/workshops/$workshopId/steps/$stepId/substeps.$substepId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexSplatRoute = ApiIndexSplatRouteImport.update({
  id: '/api/index/$',
  path: '/api/index/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerWorkshopsIndexRoute = ManagerWorkshopsIndexRouteImport.update({
  id: '/manager/workshops/',
  path: '/manager/workshops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSessionsIndexRoute = ManagerSessionsIndexRouteImport.update({
  id: '/manager/sessions/',
  path: '/manager/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSessionIdParticipantIdRoute =
  AppSessionIdParticipantIdRouteImport.update({
    id: '/app/$sessionId/$participantId',
    path: '/app/$sessionId/$participantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerWorkshopsWorkshopIdIndexRoute =
  ManagerWorkshopsWorkshopIdIndexRouteImport.update({
    id: '/manager/workshops/$workshopId/',
    path: '/manager/workshops/$workshopId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagerSessionsSessionIdIndexRoute =
  ManagerSessionsSessionIdIndexRouteImport.update({
    id: '/manager/sessions/$sessionId/',
    path: '/manager/sessions/$sessionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute =
  ManagerWorkshopsWorkshopIdStepsStepIdIndexRouteImport.update({
    id: '/manager/workshops/$workshopId/steps/$stepId/',
    path: '/manager/workshops/$workshopId/steps/$stepId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute =
  ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRouteImport.update({
    id: '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId',
    path: '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/$sessionId/$participantId': typeof AppSessionIdParticipantIdRoute
  '/manager/sessions': typeof ManagerSessionsIndexRoute
  '/manager/workshops': typeof ManagerWorkshopsIndexRoute
  '/api/index/$': typeof ApiIndexSplatRoute
  '/manager/sessions/$sessionId': typeof ManagerSessionsSessionIdIndexRoute
  '/manager/workshops/$workshopId': typeof ManagerWorkshopsWorkshopIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/$sessionId/$participantId': typeof AppSessionIdParticipantIdRoute
  '/manager/sessions': typeof ManagerSessionsIndexRoute
  '/manager/workshops': typeof ManagerWorkshopsIndexRoute
  '/api/index/$': typeof ApiIndexSplatRoute
  '/manager/sessions/$sessionId': typeof ManagerSessionsSessionIdIndexRoute
  '/manager/workshops/$workshopId': typeof ManagerWorkshopsWorkshopIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/': typeof AppIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/$sessionId/$participantId': typeof AppSessionIdParticipantIdRoute
  '/manager/sessions/': typeof ManagerSessionsIndexRoute
  '/manager/workshops/': typeof ManagerWorkshopsIndexRoute
  '/api/index/$': typeof ApiIndexSplatRoute
  '/manager/sessions/$sessionId/': typeof ManagerSessionsSessionIdIndexRoute
  '/manager/workshops/$workshopId/': typeof ManagerWorkshopsWorkshopIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId/': typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/manager'
    | '/api/rpc/$'
    | '/app/$sessionId/$participantId'
    | '/manager/sessions'
    | '/manager/workshops'
    | '/api/index/$'
    | '/manager/sessions/$sessionId'
    | '/manager/workshops/$workshopId'
    | '/manager/workshops/$workshopId/steps/$stepId'
    | '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/manager'
    | '/api/rpc/$'
    | '/app/$sessionId/$participantId'
    | '/manager/sessions'
    | '/manager/workshops'
    | '/api/index/$'
    | '/manager/sessions/$sessionId'
    | '/manager/workshops/$workshopId'
    | '/manager/workshops/$workshopId/steps/$stepId'
    | '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
  id:
    | '__root__'
    | '/'
    | '/app/'
    | '/manager/'
    | '/api/rpc/$'
    | '/app/$sessionId/$participantId'
    | '/manager/sessions/'
    | '/manager/workshops/'
    | '/api/index/$'
    | '/manager/sessions/$sessionId/'
    | '/manager/workshops/$workshopId/'
    | '/manager/workshops/$workshopId/steps/$stepId/'
    | '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppIndexRoute: typeof AppIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  AppSessionIdParticipantIdRoute: typeof AppSessionIdParticipantIdRoute
  ManagerSessionsIndexRoute: typeof ManagerSessionsIndexRoute
  ManagerWorkshopsIndexRoute: typeof ManagerWorkshopsIndexRoute
  ApiIndexSplatRoute: typeof ApiIndexSplatRoute
  ManagerSessionsSessionIdIndexRoute: typeof ManagerSessionsSessionIdIndexRoute
  ManagerWorkshopsWorkshopIdIndexRoute: typeof ManagerWorkshopsWorkshopIdIndexRoute
  ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute: typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute
  ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute: typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/index/$': {
      id: '/api/index/$'
      path: '/api/index/$'
      fullPath: '/api/index/$'
      preLoaderRoute: typeof ApiIndexSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/workshops/': {
      id: '/manager/workshops/'
      path: '/manager/workshops'
      fullPath: '/manager/workshops'
      preLoaderRoute: typeof ManagerWorkshopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/sessions/': {
      id: '/manager/sessions/'
      path: '/manager/sessions'
      fullPath: '/manager/sessions'
      preLoaderRoute: typeof ManagerSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$sessionId/$participantId': {
      id: '/app/$sessionId/$participantId'
      path: '/app/$sessionId/$participantId'
      fullPath: '/app/$sessionId/$participantId'
      preLoaderRoute: typeof AppSessionIdParticipantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/workshops/$workshopId/': {
      id: '/manager/workshops/$workshopId/'
      path: '/manager/workshops/$workshopId'
      fullPath: '/manager/workshops/$workshopId'
      preLoaderRoute: typeof ManagerWorkshopsWorkshopIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/sessions/$sessionId/': {
      id: '/manager/sessions/$sessionId/'
      path: '/manager/sessions/$sessionId'
      fullPath: '/manager/sessions/$sessionId'
      preLoaderRoute: typeof ManagerSessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/workshops/$workshopId/steps/$stepId/': {
      id: '/manager/workshops/$workshopId/steps/$stepId/'
      path: '/manager/workshops/$workshopId/steps/$stepId'
      fullPath: '/manager/workshops/$workshopId/steps/$stepId'
      preLoaderRoute: typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId': {
      id: '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
      path: '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
      fullPath: '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
      preLoaderRoute: typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppIndexRoute: AppIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  AppSessionIdParticipantIdRoute: AppSessionIdParticipantIdRoute,
  ManagerSessionsIndexRoute: ManagerSessionsIndexRoute,
  ManagerWorkshopsIndexRoute: ManagerWorkshopsIndexRoute,
  ApiIndexSplatRoute: ApiIndexSplatRoute,
  ManagerSessionsSessionIdIndexRoute: ManagerSessionsSessionIdIndexRoute,
  ManagerWorkshopsWorkshopIdIndexRoute: ManagerWorkshopsWorkshopIdIndexRoute,
  ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute:
    ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute,
  ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute:
    ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
