/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerRouteRouteImport } from './routes/manager/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as ApiIndexSplatRouteImport } from './routes/api/index.$'
import { Route as ManagerWorkshopsIndexRouteImport } from './routes/manager/workshops/index'
import { Route as ManagerSessionsIndexRouteImport } from './routes/manager/sessions/index'
import { Route as AppParticipantIdIndexRouteImport } from './routes/app/$participantId/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ManagerWorkshopsWorkshopIdIndexRouteImport } from './routes/manager/workshops/$workshopId/index'
import { Route as ManagerSessionsSessionIdIndexRouteImport } from './routes/manager/sessions/$sessionId/index'
import { Route as ManagerWorkshopsWorkshopIdStepsStepIdIndexRouteImport } from './routes/manager/workshops/$workshopId/steps/$stepId/index'
import { Route as ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRouteImport } from './routes/manager/workshops/$workshopId/steps/$stepId/substeps.$substepId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRouteRoute = ManagerRouteRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexSplatRoute = ApiIndexSplatRouteImport.update({
  id: '/api/index/$',
  path: '/api/index/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerWorkshopsIndexRoute = ManagerWorkshopsIndexRouteImport.update({
  id: '/workshops/',
  path: '/workshops/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const ManagerSessionsIndexRoute = ManagerSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => ManagerRouteRoute,
} as any)
const AppParticipantIdIndexRoute = AppParticipantIdIndexRouteImport.update({
  id: '/app/$participantId/',
  path: '/app/$participantId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerWorkshopsWorkshopIdIndexRoute =
  ManagerWorkshopsWorkshopIdIndexRouteImport.update({
    id: '/workshops/$workshopId/',
    path: '/workshops/$workshopId/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ManagerSessionsSessionIdIndexRoute =
  ManagerSessionsSessionIdIndexRouteImport.update({
    id: '/sessions/$sessionId/',
    path: '/sessions/$sessionId/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute =
  ManagerWorkshopsWorkshopIdStepsStepIdIndexRouteImport.update({
    id: '/workshops/$workshopId/steps/$stepId/',
    path: '/workshops/$workshopId/steps/$stepId/',
    getParentRoute: () => ManagerRouteRoute,
  } as any)
const ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute =
  ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRouteImport.update({
    id: '/workshops/$workshopId/steps/$stepId/substeps/$substepId',
    path: '/workshops/$workshopId/steps/$stepId/substeps/$substepId',
    getParentRoute: () => ManagerRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manager': typeof ManagerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/$participantId': typeof AppParticipantIdIndexRoute
  '/manager/sessions': typeof ManagerSessionsIndexRoute
  '/manager/workshops': typeof ManagerWorkshopsIndexRoute
  '/api/index/$': typeof ApiIndexSplatRoute
  '/manager/sessions/$sessionId': typeof ManagerSessionsSessionIdIndexRoute
  '/manager/workshops/$workshopId': typeof ManagerWorkshopsWorkshopIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app': typeof AppIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/$participantId': typeof AppParticipantIdIndexRoute
  '/manager/sessions': typeof ManagerSessionsIndexRoute
  '/manager/workshops': typeof ManagerWorkshopsIndexRoute
  '/api/index/$': typeof ApiIndexSplatRoute
  '/manager/sessions/$sessionId': typeof ManagerSessionsSessionIdIndexRoute
  '/manager/workshops/$workshopId': typeof ManagerWorkshopsWorkshopIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manager': typeof ManagerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/': typeof AppIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/app/$participantId/': typeof AppParticipantIdIndexRoute
  '/manager/sessions/': typeof ManagerSessionsIndexRoute
  '/manager/workshops/': typeof ManagerWorkshopsIndexRoute
  '/api/index/$': typeof ApiIndexSplatRoute
  '/manager/sessions/$sessionId/': typeof ManagerSessionsSessionIdIndexRoute
  '/manager/workshops/$workshopId/': typeof ManagerWorkshopsWorkshopIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId/': typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute
  '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId': typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manager'
    | '/login'
    | '/app'
    | '/manager/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/app/$participantId'
    | '/manager/sessions'
    | '/manager/workshops'
    | '/api/index/$'
    | '/manager/sessions/$sessionId'
    | '/manager/workshops/$workshopId'
    | '/manager/workshops/$workshopId/steps/$stepId'
    | '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app'
    | '/manager'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/app/$participantId'
    | '/manager/sessions'
    | '/manager/workshops'
    | '/api/index/$'
    | '/manager/sessions/$sessionId'
    | '/manager/workshops/$workshopId'
    | '/manager/workshops/$workshopId/steps/$stepId'
    | '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
  id:
    | '__root__'
    | '/'
    | '/manager'
    | '/login'
    | '/app/'
    | '/manager/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/app/$participantId/'
    | '/manager/sessions/'
    | '/manager/workshops/'
    | '/api/index/$'
    | '/manager/sessions/$sessionId/'
    | '/manager/workshops/$workshopId/'
    | '/manager/workshops/$workshopId/steps/$stepId/'
    | '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManagerRouteRoute: typeof ManagerRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  AppParticipantIdIndexRoute: typeof AppParticipantIdIndexRoute
  ApiIndexSplatRoute: typeof ApiIndexSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/index/$': {
      id: '/api/index/$'
      path: '/api/index/$'
      fullPath: '/api/index/$'
      preLoaderRoute: typeof ApiIndexSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/workshops/': {
      id: '/manager/workshops/'
      path: '/workshops'
      fullPath: '/manager/workshops'
      preLoaderRoute: typeof ManagerWorkshopsIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/sessions/': {
      id: '/manager/sessions/'
      path: '/sessions'
      fullPath: '/manager/sessions'
      preLoaderRoute: typeof ManagerSessionsIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/app/$participantId/': {
      id: '/app/$participantId/'
      path: '/app/$participantId'
      fullPath: '/app/$participantId'
      preLoaderRoute: typeof AppParticipantIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/workshops/$workshopId/': {
      id: '/manager/workshops/$workshopId/'
      path: '/workshops/$workshopId'
      fullPath: '/manager/workshops/$workshopId'
      preLoaderRoute: typeof ManagerWorkshopsWorkshopIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/sessions/$sessionId/': {
      id: '/manager/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/manager/sessions/$sessionId'
      preLoaderRoute: typeof ManagerSessionsSessionIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/workshops/$workshopId/steps/$stepId/': {
      id: '/manager/workshops/$workshopId/steps/$stepId/'
      path: '/workshops/$workshopId/steps/$stepId'
      fullPath: '/manager/workshops/$workshopId/steps/$stepId'
      preLoaderRoute: typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
    '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId': {
      id: '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
      path: '/workshops/$workshopId/steps/$stepId/substeps/$substepId'
      fullPath: '/manager/workshops/$workshopId/steps/$stepId/substeps/$substepId'
      preLoaderRoute: typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRouteImport
      parentRoute: typeof ManagerRouteRoute
    }
  }
}

interface ManagerRouteRouteChildren {
  ManagerIndexRoute: typeof ManagerIndexRoute
  ManagerSessionsIndexRoute: typeof ManagerSessionsIndexRoute
  ManagerWorkshopsIndexRoute: typeof ManagerWorkshopsIndexRoute
  ManagerSessionsSessionIdIndexRoute: typeof ManagerSessionsSessionIdIndexRoute
  ManagerWorkshopsWorkshopIdIndexRoute: typeof ManagerWorkshopsWorkshopIdIndexRoute
  ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute: typeof ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute
  ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute: typeof ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute
}

const ManagerRouteRouteChildren: ManagerRouteRouteChildren = {
  ManagerIndexRoute: ManagerIndexRoute,
  ManagerSessionsIndexRoute: ManagerSessionsIndexRoute,
  ManagerWorkshopsIndexRoute: ManagerWorkshopsIndexRoute,
  ManagerSessionsSessionIdIndexRoute: ManagerSessionsSessionIdIndexRoute,
  ManagerWorkshopsWorkshopIdIndexRoute: ManagerWorkshopsWorkshopIdIndexRoute,
  ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute:
    ManagerWorkshopsWorkshopIdStepsStepIdIndexRoute,
  ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute:
    ManagerWorkshopsWorkshopIdStepsStepIdSubstepsSubstepIdRoute,
}

const ManagerRouteRouteWithChildren = ManagerRouteRoute._addFileChildren(
  ManagerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManagerRouteRoute: ManagerRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  AppIndexRoute: AppIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  AppParticipantIdIndexRoute: AppParticipantIdIndexRoute,
  ApiIndexSplatRoute: ApiIndexSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
